#!/bin/sh

sleep 5

ip link set wlan0 up

sleep 2
wpa_supplicant -B -i wlan0 -c /home/spondbob/projects/bikinibottom-mode/etc/wpa_supplicant.conf
ip addr add 192.168.0.8/24 broadcast 192.168.0.255 dev wlan0
ip route add default via 192.168.0.1

# Fix resolv.conf
echo "# Generated by resolvconf" > /etc/resolv.conf
echo "nameserver 192.168.0.1" > /etc/resolv.conf

