#!/bin/sh

sleep 5

ip link set eth0 up

sleep 2
ip addr add 169.254.1.134/16 broadcast 169.254.1.255 dev eth0
ip route add default via 169.254.1.131

# Fix resolv.conf
rm /etc/resolv.conf
echo "# Generated by resolvconf" > /etc/resolv.conf
echo "nameserver 169.254.1.131" > /etc/resolv.conf
