#!/bin/sh

sleep 5

ip link set eth0 up

sleep 2
ip addr add 192.168.137.4/24 broadcast 192.168.137.255 dev eth0
ip route add default via 192.168.137.1

# Fix resolv.conf
echo "# Generated by resolvconf" > /etc/resolv.conf
echo "nameserver 192.168.137.1" > /etc/resolv.conf

