#!/bin/sh

sleep 2

ip link set wlan0 up

sleep 2
wpa_supplicant -B -i wlan0 -c /boot/bikinibottom-mode/etc/wpa_supplicant.conf

# Request DHCP and tweets the IP
dhcpcd wlan0
sleep 3
sh /home/spondbob/projects/tweety/tweet_my_ip.sh wlan0

# Static IP
#ip addr add 192.168.201.90/24 broadcast 192.168.201.255 dev wlan0
#ip route add default via 192.168.201.1

# Fix resolv.conf
#echo "# Generated by resolvconf" > /etc/resolv.conf
#echo "nameserver 192.168.201.1" > /etc/resolv.conf

