#!/bin/sh

sleep 3

ip link set wlan0 up

sleep 2
wpa_supplicant -B -i wlan0 -c /boot/bikinibottom-mode/etc/wpa_supplicant.conf
ip addr add 192.168.53.90/24 broadcast 192.168.53.255 dev wlan0
ip route add default via 192.168.53.1

# Fix resolv.conf
echo "# Generated by resolvconf" > /etc/resolv.conf
echo "nameserver 192.168.53.1" > /etc/resolv.conf

